### PR TITLE
[fix] Fix Pool setting results in error 400

### PR DESCRIPTION
**Pull request by mleone87**

### CODE REVIEW

**Comment by mleone87** [comment]
should fix https://github.com/Telmate/proxmox-api-go/issues/306

**Comment by Tinyblargon** [comment]
@mleone87

We do update the pool there, so I'm not sure why that `pool` property is set. I think it's safe to remove the offending test cases.
https://github.com/Telmate/proxmox-api-go/blob/586199ea9da20d267441fad17937d96f01a2d00c/proxmox/config_qemu.go#L977-L978

**Comment by mleone87** [comment]
@Tinyblargon 99% confident, waiting for your 👍

**Comment by Tinyblargon** [comment]
@mleone87 tested it, guest got added to pool so everything works.

**Pull request merged**
