### PR TITLE
fix: do not expose empty cipassword to API

### PR DESCRIPTION
**Pull request by jay7x**
Fixes https://github.com/Telmate/terraform-provider-proxmox/issues/1097

### CODE REVIEW

**Comment by Tinyblargon** [comment]
@jay7x thank you for your contribution, could you add a test case to cement this behavior.

This is the test I'm referring to:
https://github.com/Telmate/proxmox-api-go/blob/032717b543a596ebae3013da4cda592052a02d17/proxmox/config_qemu_test.go#L16

**Comment by jay7x** [comment]
I'll try to add it this weekend :)

**Comment by jay7x** [comment]
Later is better than never! I added a case when `cipassword` should be deleted when set to an empty value. Not really sure it is meaningful at all, but it behaves the same as `ciuser` now.
@Tinyblargon let me know if you'd prefer to drop this latest behavior change or split the PR.

**Comment by Tinyblargon** [comment]
@jay7x I'll try to review it tomorrow. Setting the password to an empty string in the GUI also deletes it. Therefore, how you implement it is the correct behavior.

**Comment by Tinyblargon** [comment]
@jay7x everything looks good.

**Pull request merged**
