### PR TITLE
fix(CreateVm): Add PXE boolean option to config

### PR DESCRIPTION
**Pull request by sygibson**
This pull requests adds a new Config directive of `pxe` type which can be used to indicate that a PXE boot is being requested of the Virtual Machine.

On its own, this will not actually implement the PXE boot capability.  That is ultimately implemented by use of a correct set of `boot` directives defining the Network Boot option first (eg `ncd`, or `order=net0;scsi0`).

This addresses Issue #153 .

### CODE REVIEW

**Comment by mleone87** [comment]
I dont get this PR.

As you say, just put net0 at first place in your boot directive and it will be pxe.

Proxmox api does not provide any "pxe" directive and we tend to stick to proxmox api returned struct for config fields

**Comment by sygibson** [comment]
Thank  you for the comments.  I am using the Telmate/proxmox-api-go library downstream in the Telmate/terraform-provider-proxmox.

I have a PR on the way in for that code, to allow PXE boot as a valid type.  I understand that the option `PXE` might not be a specific API, and as such, adding it here for completeness sake may be unusual.

Within the terraform-provider-proxmox code, I am validating that the `boot` options contain a network boot specification; if the `pxe` config value is set `true`.  There is no way to determine intent and then check the `boot` options for correctness without something similar to a `pxe` argument that can invoke those safety checks.

As I was working through the changes to enable the PXE boot scenario, I believed it would be "correct" to expose that argument within the underlying proxmox-api-go library.  Ultimately, a similar "safety" check could be implemented in that library for that given use case.

I am happy to defer to your opinions on that, and just leave the PXE option and safety check in the terraform-provider-proxmox code.

I would also be happy to port the Golang code that performs the regexp string matches on the `boot` option in to this library; should it be decided that was a worthy endeavor that lent some credence to the `pxe` flag and option being exposed in proxmox-api-go.

**Comment by mleone87** [comment]
ok, now its more clear!

I agree that a "pxe" boot option would be useful too, along with clone and iso ones

Do you need to add more commits to this PR?

**Comment by sygibson** [comment]
"That depends".... :-) 

Do you want `boot` flag validation enabled in the base library (`Telemate/proxmox-api-go`)?  If so - I'm happy to pull over those bits of code, and validate `boot` options against the regexp; if the `pxe` flag is set.  

From an operational perspective, I'd suggest introducing another Config option ... something like `pxe_boot_regexp`, which would be an Array of Strings of regexp to apply to the `boot` test logic.  If not set; then default to my current two regexp strings:

```
"^n.*$", "^order=net.*$"
```

I would add this; as upstream changes to how the `boot` string appears can then be quickly reworked on the fly without breaking functionality.  An operator could override the boot regexp string matches until a code fix for the compiled libraries can be adjusted appropriately. 

I'm also not 100% confident I've caught all of the possible _correct_ values with my current two regexp strings.  Those are just the formats I've personally run in to in the wild; which could be variations like:

```
ncd                 # old format for 'network', 'cdrom', 'disk' ordering
order=net0;scsi0    # new format for first network device, then first scsi disk
```

I'm uncertain about the impact of my change suggestion - as I have not directly used or interacted with the `proxmox-api-go` library.  If there are some public examples of this in use with input configuration stanzas, that would help me understand the impact of my change suggestion.   My only implementation / use experience is from minimal play with the `terraform-provider-proxmox` use ... which I am using to fully automated Infrastructure Pipelines against Proxmox clusters.

Thank you.

**Comment by mleone87** [comment]
Thanks for your detailed explanation.
I would leave this API client as it is and move all the complexity in the terraform provider. If one would implement PXE boot directly using this client it should independently provide the correct syntax to the CreateVM function(via JSON file or implementig the module in it's own code).
Speaking of the terraform provider, this means that we will have the following mutually exclusive fields

1. iso
2. clone
3. pxe

In the `resourceVmQemuCreate` function in the provider should happen all the regexp/formatting magic.

This is how I would implement it.

It would be a nice occasion to reformat the aforementioned function to be more clear.

Ler me know what do you think :)

**Comment by sygibson** [comment]
@mleone87 - thank you for the pointers ... I think I've reworked the `add-pxe` branch to align with what you have requested.  Summary:

- removed the `params` add of `pxe`; this does not validate against the API
- leave the `QemuPxe` as a valid struct to define the JSON config option (`pxe: true`)
- in `main.go`, fix the `installQemu` handling to support ISO and PXE modes both
- `if` condition the ISO mode wait for install, and ISO unmount / reboot operation to complete
- slightly enhanced the log output to identify ISO -vs- PXE create modes

I have the downstream `terraform-provider-proxmox` changes ready to go, which does the validation of the mutually exclussive `clone`, `iso`, and `pxe` modes.  I need to re-test everything with these changes.

I will submit a pull request on that repo tomorrow after I get a chance to finish testing.  Please advise if any changes or rework of this pull request are needed.

Thank you.

**Comment by sygibson** [comment]
@mleone87 - the PR has been updated as described ... if you could please review, and if approved, pull it in ? 

Thank you.
~~shane

**Pull request merged**
