### PR TITLE
fix: Disk incorrectly formatted with `lvm` back-end

### PR DESCRIPTION
**Pull request by Tinyblargon**
Ran into a bug where the disk format was returned empty by the library.

Apparently the lvm, and file storage back-ends use different syntax for the disks:
- file: `storage:100/vm-100-disk-0.raw`
- lvm: `storage:vm-100-disk-0`

### CODE REVIEW

**Comment by Tinyblargon** [comment]
Okay so upon even further investigation, it can create, delete and read the disk inforamtion when backed by LVM, but not update it.

**Comment by mleone87** [comment]
safe to merge @Tinyblargon ?

**Comment by Tinyblargon** [comment]
@mleone87 Still working on this one, sorry for making a premature pull request.

I now know the full extend of what needs to change tho.

These 2 parts of the code I'm gonna extract as a function as the code for parsing the disk info is sadly gonna get more complicated:

https://github.com/Telmate/proxmox-api-go/blob/master/proxmox/config_qemu_disk.go#L208-L216
https://github.com/Telmate/proxmox-api-go/blob/master/proxmox/config_qemu_disk.go#L305-L333

**Comment by Tinyblargon** [comment]
@mleone87 It's ready to merge.

Work Done:
- when using a storage back-end like lvm disks can now be created, updated, read and deleted reliably.
- Introduced a private type `diskSyntaxEnum` to keep track of which disk syntax should be used when updating the disk.
- Fixed an issue where node would not be set in `ConfigQemu` af11eb2f59353382a606d0353be0c1afca06dbf7
- Added tests for everything.
- [proxmox/config_qemu_test.go](https://github.com/Telmate/proxmox-api-go/pull/292/files#diff-99b4ccf6665d08a6de5fcd49d59de2ecf3a0dcb8e67e0984851a361a800206fc) did diff a little weirdly. TLDR only the names of existing tests have been changed, everything else is added tests.

The following code was moved to its own functions:
https://github.com/Telmate/proxmox-api-go/blob/0b0c911a0a512b0ddd8642a9745d9ade4411d1c2/proxmox/config_qemu_disk.go#L208-L216

https://github.com/Telmate/proxmox-api-go/blob/0b0c911a0a512b0ddd8642a9745d9ade4411d1c2/proxmox/config_qemu_disk.go#L305-L333

**Pull request merged**
