### PR TITLE
feat: add pcie support for QEMU

### PR DESCRIPTION
**Pull request by BenediktBertsch**
Create functionality to add pcie cards.

### CODE REVIEW

**Comment by mleone87** [comment]
what's a "pcis" api json response?

**Comment by BenediktBertsch** [comment]
@mleone87 Hey the pcis would be the [hostpci[n]](https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/config).
The qemu.json would look like this with one e.g. PCI device:
<pre>... <br>
&emsp;"pcis": {<br>
&emsp;        "0": {<br>
&emsp;            "pciid": "0000:01:00.1"<br>
&emsp;        }<br>
&emsp;}<br>
&emsp;...</pre>

Now we could add GPU's for transcoding.
Do you prefer more `json:"hostpci,omitempty"` like in the proxmox API?

**Comment by mleone87** [comment]
hello @BenediktBertsch 
I would like to use the proxmox api names for everything to avoid confusion

The json would look like
```

    "hostpci": {
      "0": {
        "host": "0000:01:00.2",
        "rombar": 0
      }
    }
```

Your code includes only the pciid, but I would at least support all parameters, the code to include all parameters would be like that, but there are other examples to create the parameters, this one works though

```
func (c ConfigQemu) CreateQemuPCIsParams(vmID int, params map[string]interface{}) error {
	// For new style with multi pci device.
	for pciConfID, pciConfMap := range c.QemuPCIDevices {
		qemuPCIName := "hostpci" + strconv.Itoa(pciConfID)
		var pcistring bytes.Buffer
		//pciId := pciConfMap["pciid"].(string)
		for elem := range pciConfMap {
			pcistring.WriteString(elem)
			pcistring.WriteString("=")
			pcistring.WriteString(fmt.Sprintf("%v", pciConfMap[elem]))
			pcistring.WriteString(",")
		}

		// Add back to Qemu prams.
		params[qemuPCIName] = strings.TrimSuffix(pcistring.String(), ",")
	}
	return nil
}
```

**Comment by BenediktBertsch** [comment]
@mleone87 Changed as you recommended, ty for looking over it.

**Pull request merged**
