### PR TITLE
Add EFI features

### PR DESCRIPTION
**Pull request by alex-sector**
This commit allows more complex EFI configurations. It allows
    to create Secure Boot VM with default keys enrolled in it.

### CODE REVIEW

**Comment by mleone87** [comment]
will you provide also PR for terraform provider about this change?

**Comment by mleone87** [comment]
@alex-sector if you want to submit you PR to the provider repo I'll do a merge soon

**Comment by alex-sector** [comment]
@mleone87 Thanks, the PR has been submit last week here : hashicorp/packer-plugin-proxmox#90

**Comment by alex-sector** [comment]
@mleone87 : Can you merge the pull request on [hashicorp](https://github.com/hashicorp/packer-plugin-proxmox/pull/90) ?. New patches are now in conflict and need rebasing [here](https://github.com/hashicorp/packer-plugin-proxmox/pull/93).

Regards,

**Pull request merged**
